spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/studentdata
spring.datasource.username=postgres
spring.datasource.password=saru123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api

